[tool.poetry]
name = "data"
version = "0.1.0"
description = ""
authors = ["Tom Forbes <tom@tomforb.es>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "pypi_data", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
typer = { extras = ["all"], version = "^0.9.0" }
pygithub = "^2.1.1"
duckdb = "^0.9.2"
tqdm = "^4.66.1"
more-itertools = "^10.1.0"
prql-python = "^0.10.1"
psutil = "^5.9.6"

[tool.poetry.scripts]
pypi-data = "pypi_data.cli:app"

[tool.poetry.group.dev.dependencies]
black = "^23.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
