[tool.poetry]
name = "data"
version = "0.1.0"
description = ""
authors = ["Tom Forbes <tom@tomforb.es>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "pypi_data", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.11"
polars = {extras = ["pyarrow"], version = "^0.18.7"}
requests = "^2.31.0"
typer = {extras = ["all"], version = "^0.9.0"}
pygithub = "^1.59.0"

[tool.poetry.scripts]
pypi-data = "pypi_data.cli:app"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
