[tool.poetry]
name = "data"
version = "0.1.0"
description = ""
authors = ["Tom Forbes <tom@tomforb.es>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "pypi_data", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"
typer = { extras = ["all"], version = "^0.12.1" }
pygithub = "^2.3.0"
duckdb = "^0.10.1"
tqdm = "^4.66.2"
more-itertools = "^10.2.0"
prql-python = "^0.11.2"
psutil = "^5.9.8"

[tool.poetry.scripts]
pypi-data = "pypi_data.cli:app"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
