on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"


name: Delete Draft Releases older than 1 days

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
