on:
  workflow_dispatch:

name: Delete Draft Releases older than 1 days

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: sgpublic/delete-release-action@v1.0
        with:
          release-drop: true
          release-keep-count: 2
          release-drop-tag: true
          pre-release-drop: true
          pre-release-keep-count: -1
          pre-release-drop-tag: true
          draft-drop: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
