# On every push this script is executed
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

concurrency: data

name: Build data
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          cache: pip

      - name: Install deps
        run: uv sync --frozen

      - name: Generate token
        id: generate_token
        uses: pypi-data/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Generate Repo Metadata
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: uv run pypi-data load-repos repos.json.zstd

      - name: "Set current date as env variable"
        run: |
          echo "tag_name=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT
        id: version

      - name: Create Release
        id: create-release
        uses: shogo82148/actions-create-release@v1
        with:
          draft: true
          release_name: ${{ steps.version.outputs.tag_name }}
          tag_name: ${{ steps.version.outputs.tag_name }}
          commitish: ${{ github.sha }}

      - name: Upload Assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ needs.generate-matrix.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/repos.json.zstd
          asset_name: repos.json.zstd

#
#      - env:
#          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
#        run: |
#          uv run pypi-data print-git-urls > links/repositories.txt
#          uv run pypi-data print-git-urls --ssh-urls > links/repositories_ssh.txt
#
#      - uses: EndBug/add-and-commit@v9
#        with:
#          add: |
#            links/repositories.txt
#            links/repositories_ssh.txt
#          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
#          author_name: "commit-bot"
#          message: "Add repository URLs"
#          push: true
#          fetch: true
#          pull: '--rebase --autostash'
