on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 0 * * *"

name: Build unique python files
concurrency: build-unique-python

jobs:
  build_and_test:
    name: Compile toolchain
    runs-on: ubuntu-latest
    if: github.repository == 'pypi-data/data'
    env:
      RUST_BACKTRACE: "1"
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: unique-python-files-

      - name: Build optimized release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile=optimized
        env:
          RUSTFLAGS: '-C target-cpu=native'

      - name: Run
        run: |
          ./target/optimized/data links/dataset.txt data/
